# Generated by Django 4.2.7 on 2023-11-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApi", "0002_userjwtwhitelisttoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(default="Blog/dummy.png", upload_to="Blog/"),
        ),
    ]
